#+EXPORT_FILE_NAME: ../../../heap/Is_Heap.org
#+OPTIONS: author:nil title:nil toc:nil
** The Is_Heap function

The ~Is_Heap~ functions verifies that the data given as parameter to the function respects the properties definig the heap data structure. 
Its signature reads:

#+BEGIN_SRC ada 
function Is_Heap(H : Heap) return Boolean
#+END_SRC

*** The Is_Heap_Def predicate

In order to specify our function we need to write a predicate formally defining what a correct heap is:

	#+INCLUDE: ../../../spec/heap_predicates.ads :src ada :range-begin "function Is_Heap_Def" :range-end "\s-*(\(.*?\(?:\n.*\)*?\)*)\s-*\([^;]*?\(?:\n[^;]*\)*?\)*;" :lines "15-22"

This predicate checks that the last valid index of our record is less than the actual (fixed) sized of the array,
and that our heap is either empty or that for all index ~I~ greater than two, then the value at index ~I~ is less than the value at the parent of ~I~.

*** Specification of Is_Heap

The ~Is_Heap~ can be specified as follows:

	#+INCLUDE: ../../../heap/is_heap_p.ads :src ada :range-begin "function Is_Heap" :range-end "\s-*(\(.*?\(?:\n.*\)*?\)*)\s-*\([^;]*?\(?:\n[^;]*\)*?\)*;" :lines "7-9"

There is no precondition on our ~Heap~ record, and the only postcondition is that ~Is_Heap~ returns the same result as our formaly defined predicate.

*** Implementation of Is_Heap

Is heap can be implemented in the following way:

	#+INCLUDE: ../../../heap/is_heap_p.adb :src ada :range-begin "function Is_Heap" :range-end "End Is_Heap;" :lines "4-36"

We first check that the membe ~Size~ of ~H~ is valid, i.e. less that the length of the array,
and then we verify that for each index that can be a child (~Child >=2~), the value found at its parent's index is greater thatn the value found at the child's index.


Here the loop invariants specify that:
- the variables ~parent~ and ~child~ are in the corect range, and order
- that ~Child~ is indeed a child of ~Parent~ 
- that the ~Heap~ record constituted of the original array, but with size set to ~Child~ is a heap. This checks that the fisrt ~Child~ values of ~H.A~ form a heap.


With this specification and implementation, ~GNATprove~ proves everything.
# Local Variables:
# ispell-dictionary: "english"
# End:
