* Non-mutating algorithms

  This directory contains the specification and implementation files
  for the following algorithms: ~Find~, ~Find_First_Of~,
  ~Adjacent_Find~, ~Equal~, ~Search~, ~Search_N~, ~Find_End~ and
  ~Count~. As usual, ghost functions used in specification are located
  in the ~spec~ directory at project root.

  Each function is specified and defined in its own
  files. Specifications and implementations are defined in
  packages. To avoid name clashes with functions, packages names have
  a ~_P~ suffixes, hence the file names.

  The functions are the corresponding files are presented in the
  following table:

  | function | files                        | comments                                                   |
  |----------+------------------------------+------------------------------------------------------------|
  | [[./Find.org][Find]]     | ~naive_find_p.ads~           | a first naive version of ~Find~                            |
  |          | ~naive_find_p.adb~           |                                                            |
  |          | ~naive_find_contract_pb.ads~ | a simple example of contract non completeness/disjointness |

# Local Variables:
# ispell-dictionary: "english"
# End:
