#+EXPORT_FILE_NAME: ../../../mutating/Copy.org
#+OPTIONS: author:nil title:nil toc:nil

** The Copy Algorithm

The ~Copy~ procedure copies the content of an array into another array. Its signature is :

#+BEGIN_SRC ada
procedure Copy(A : T_Arr; B : in out T_Arr)
#+END_SRC

The usefulness of this procedure could be doubted in ADA, since the simple commande ~A := B~ achieves 
the same goal for arrays of same length. Our procedure only works with arrays of same length, since copying 
part of an array into another can be achived through slicing.

The purpose of this document being to prove classicals algorithms, and compare what can be done in ADA
 with what was done in C++ in *ACSL by Example*, where this procedure makes sense.

*** Specification of Copy

~Copy~ specification is:

	#+INCLUDE: ../../../mutating/copy_p.ads :src ada :range-begin "procedure Copy" :range-end "\s-*(\(.*?\(?:\n.*\)*?\)*)\s-*\([^;]*?\(?:\n[^;]*\)*?\)*;" :lines "7-10"


The precondition expresses the fact that ~A~ and ~B~ should be of the same size.
The post condition expresses that ~A~ and ~B~ are equal element-wise.

*** Implementation of Copy

One implementation for Copy is:

#+INCLUDE: ../../../mutating/copy_p.adb :src ada :range-begin "procedure Copy" :range-end "End Copy;" :lines "4-15"

Here the loop variant is classicaly ~I~, and the loop invariant specifies that for all indexes ~K~ lesser
than ~I~, then ~A(K) = B(B'First +(K - A'First))~, i.e. we have a partial copy of the first ~I-A'First~ indexes of ~A~ in ~B~.

With this specification and implementation, when using ~gnatprove~ everything is proved.
